apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  name: postgresql
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deployment-config.name: postgresql
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment-config.name: postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: root
        - name: POSTGRESQL_PASSWORD
          value: toor
        - name: POSTGRESQL_DATABASE
          value: catalog_development
        image: docker.io/centos/postgresql-10-centos7:latest
        imagePullPolicy: IfNotPresent
        name: postgres
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: postgresql
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment-config.name: postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
