apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: catalog-dev
  name: catalog-dev-api
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: catalog-dev-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
